# docker compose down; docker compose up;
services:

  api01:
    network_mode: host
    image: ${REGISTRY_USERNAME:-faermanj}/peecs:${PEECS_VERSION:-0.1.0}
#    build: ./peecs
    hostname: api01
    container_name: api01
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9001/members/1/balance"]
      interval: 1s
      retries: 10
    environment:
      - RINHA_SHARD=0
      - QUARKUS_HTTP_PORT=9001
      - QUARKUS_BANNER_ENABLED=false
      - QUARKUS_HTTP_IDLE_TIMEOUT=45
      - QUARKUS_VERTX_MAX_EVENT_LOOP_EXECUTE_TIME=10S
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://127.0.0.1:5400/rinha
      - QUARKUS_DATASOURCE_REACTIVE_CACHE_PREPARED_STATEMENTS=true
      - QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=40
      - QUARKUS_DATASOURCE_USERNAME=rinha
      - QUARKUS_DATASOURCE_PASSWORD=123
      - QUARKUS_MICROMETER_ENABLED=false
      - QUARKUS_LOG_LEVEL=ERROR
      - QUARKUS_LOG_CATEGORY__caravanacloud__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.quarkus__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.postgresql__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.netty__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.vertx__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.jboss__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.flyway__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.smallreye__LEVEL=INFO
    ports:
      - "9001:9001"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "150MB"

  api02:
    network_mode: host
    image: ${REGISTRY_USERNAME:-faermanj}/peecs:${PEECS_VERSION:-0.1.0}
#    build: ./peecs
    hostname: api02
    container_name: api02
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9002/members/1/balance"]
      interval: 1s
      retries: 10
    environment:
      - RINHA_SHARD=1
      - QUARKUS_HTTP_PORT=9002
      - QUARKUS_BANNER_ENABLED=false
      - QUARKUS_HTTP_IDLE_TIMEOUT=45
      - QUARKUS_VERTX_MAX_EVENT_LOOP_EXECUTE_TIME=10S
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://127.0.0.1:5400/rinha
      - QUARKUS_DATASOURCE_REACTIVE_CACHE_PREPARED_STATEMENTS=true
      - QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=40
      - QUARKUS_DATASOURCE_USERNAME=rinha
      - QUARKUS_DATASOURCE_PASSWORD=123
      - QUARKUS_MICROMETER_ENABLED=false
      - QUARKUS_LOG_LEVEL=ERROR
      - QUARKUS_LOG_CATEGORY__caravanacloud__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.postgresql__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.netty__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.vertx__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.jboss__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.flyway__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.smallreye__LEVEL=INFO
    ports:
      - "9002:9002"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "150MB"
 

  lb:
    hostname: lb
    container_name: lb
    network_mode: host 
    image: nginx:latest
#    image: haproxy:2.9.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
#    depends_on:
#      api01:
#        condition: service_healthy
#      api02:
#        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    healthcheck:
      test: ["CMD", "sleep", "3"]
      # test: ["CMD", "curl", "-f", "http://127.0.0.1:9999/members/1/balance"]
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "35MB"

#  warmup:
#    hostname: warmup
#    container_name: warmup
#    network_mode: host 
#    image: fedora:39
  #  depends_on:
  #    lb:
  #      condition: service_healthy
#    command: |
#      /bin/bash -c "echo 'warmuping'; sleep 3; \
#              for i in \$(seq 1 150); \
#              do \
#                echo -n \. \$i; \
#                curl -s http://127.0.0.1:9999/members/333/balance > /dev/null  & \
#                curl -s -H 'Content-Type: application/json' -d '{\"amount\": 0, \"kind\": \"d\", \"description\": \"warmup\"}' http://127.0.0.1:9999/members/333/transactions > /dev/null  & \
#              done; 
#              wait; 
#              echo 'warmup done';"
#    deploy:
#      resources: 
#        limits:
#          cpus: "0.05"
#          memory: "35MB"

  
  db:
    network_mode: host
    image: postgres:latest
    hostname: db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5400:5400"
    expose:
      - "5400"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'  
    deploy:
      resources: 
        limits:
          cpus: "0.85"
          memory: "180MB"
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "rinha", "--port", "5400"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 3s
