BEGIN;
/*
 * Copyright (c) 2024.
 * Julio Cezar Riffel
 * https://www.linkedin.com/in/julio-cezar-riffel/
 * https://github.com/julioriffel
 *
 */

--
-- Create model Cliente
--
CREATE UNLOGGED TABLE "conta_corrente_cliente"
(
    "id"     bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "limit" integer NOT NULL
);
--
-- Create model Transacao
--
CREATE UNLOGGED TABLE "conta_corrente_transacao"
(
    "id"           bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "kind"         varchar(1)               NOT NULL,
    "amount"        integer                  NOT NULL,
    "description"    varchar(10)              NOT NULL,
    "submitted_at" timestamp with time zone NOT NULL,
    "cliente_id"   bigint                   NOT NULL
);
--
-- Raw SQL operation
--
INSERT INTO conta_corrente_cliente (id, limit)
VALUES (1, 100000),
       (2, 80000),
       (3, 1000000),
       (4, 10000000),
       (5, 500000);
-- ALTER TABLE "conta_corrente_transacao"
--     ADD CONSTRAINT "conta_corrente_trans_cliente_id_2ee27b48_fk_conta_cor" FOREIGN KEY ("cliente_id") REFERENCES "conta_corrente_cliente" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "conta_corrente_transacao_cliente_id_2ee27b48" ON "conta_corrente_transacao" ("cliente_id");
COMMIT;