/*
 * Copyright (c) 2024.
 * Julio Cezar Riffel
 * https://www.linkedin.com/in/julio-cezar-riffel/
 * https://github.com/julioriffel
 */

BEGIN;

CREATE UNLOGGED TABLE "cliente"
(
    "id"     bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "limit" integer NOT NULL
);

CREATE UNLOGGED TABLE "transacao"
(
    "id"           bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "kind"         varchar(1)               NOT NULL,
    "amount"        integer                  NOT NULL,
    "description"    varchar(10)              NOT NULL,
    "submitted_at" timestamp with time zone NOT NULL,
    "cliente_id"   bigint                   NOT NULL
);

INSERT INTO cliente (id, limit)
VALUES (1, 100000),
       (2, 80000),
       (3, 1000000),
       (4, 10000000),
       (5, 500000);


COMMIT;




