SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public."members" (
    "Id" integer NOT NULL,
    "Limite" integer NOT NULL,
    "Saldo" integer NOT NULL
);

ALTER TABLE public."members" OWNER TO postgres;

ALTER TABLE public."members" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."members_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."transactions" (
    "Id" integer NOT NULL,
    "Valor" integer NOT NULL,
    "Tipo" character(1) NOT NULL,
    "Descricao" text NOT NULL,
    "Realizada_Em" timestamp with time zone NOT NULL,
    "ClienteId" integer NOT NULL
);


ALTER TABLE public."transactions" OWNER TO postgres;

ALTER TABLE public."transactions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."transactions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

COPY public."members" ("Id", "Limite", "Saldo") FROM stdin;
1	100000	0
2	80000	0
3	1000000	0
4	10000000	0
5	500000	0
\.

SELECT pg_catalog.setval('public."members_Id_seq"', 1, false);

SELECT pg_catalog.setval('public."transactions_Id_seq"', 1, false);

ALTER TABLE ONLY public."members"
    ADD CONSTRAINT "PK_members" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."transactions"
    ADD CONSTRAINT "PK_Transacaoes" PRIMARY KEY ("Id");

CREATE INDEX "IX_Transacaos_ClienteId" ON public."transactions" USING btree ("ClienteId");

ALTER TABLE ONLY public."transactions"
    ADD CONSTRAINT "FK_transactions_members_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES public."members"("Id") ON DELETE CASCADE;
