CREATE UNLOGGED TABLE "clientes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "limit" INTEGER NOT NULL,
    "current_balance" INTEGER NOT NULL
);

alter table clientes add constraint current_balance check (
    current_balance > 0
    or abs(current_balance) <= limit
);

INSERT INTO clientes VALUES (1, 100000, 0);
INSERT INTO clientes VALUES (2, 80000, 0);
INSERT INTO clientes VALUES (3, 1000000, 0);
INSERT INTO clientes VALUES (4, 10000000, 0);
INSERT INTO clientes VALUES (5, 500000, 0);

CREATE UNLOGGED TABLE "transactions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "amount" INTEGER NOT NULL,
    "kind" CHAR(1) DEFAULT 'd' CHECK (kind IN ('d', 'c')) NOT NULL,
    "description" VARCHAR(10) NOT NULL,
    "submitted_at" timestamp with time zone NOT NULL DEFAULT (NOW ()),
    "cliente_id" INTEGER NOT NULL,
    FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id")
);
